imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@UserBundle/Resources/config/services.yml" }
    - { resource: "@ScolariteBundle/Resources/config/services.yml" }
    - { resource: "@SanteBundle/Resources/config/services.yml" }
    - { resource: "@BabySittingBundle/Resources/config/services.yml" }
    - { resource: "@EspritApiBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    app.path.urgence_images: /web/images/urgence
    app.path.convention_images: /web/images/convention
    app.path.product_images: /web/images/publication
    app.path.users_images: /web/images/users


framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: UserBundle\Entity\User
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"
    #pour personaliser le formulaire d'inscription
    registration:
        form:
            type: AppBundle\Form\RegistrationType

vich_uploader:
    db_driver: orm
    mappings:
        adresse_image:
            uri_prefix: /images/adresses
            upload_destination: '%kernel.project_dir%/web/images/adresses'
            namer:
                service: vich_uploader.namer_uniqid
        parascolaire_image:
                    uri_prefix: /images/parascolaires
                    upload_destination: '%kernel.project_dir%/web/images/parascolaires'
                    namer:
                        service: vich_uploader.namer_uniqid
        urgence_images:
            uri_prefix: '%app.path.urgence_images%'
            upload_destination:  '%kernel.root_dir%/../web/images/urgence' #'%kernel.project_dir%/web/images/urgence'
            namer:
                service: vich_uploader.namer_uniqid

        convention_images:
            uri_prefix: '%app.path.convention_images%'
            upload_destination:  '%kernel.root_dir%/../web/images/convention' #'%kernel.project_dir%/web/images/urgence'
            namer:
                service: vich_uploader.namer_uniqid

        product_images:
            uri_prefix:         /images/publication
            upload_destination: '%kernel.root_dir%/web/images/publication'
            namer:
                service: vich_uploader.namer_uniqid

        users_images:
            uri_prefix: '%app.path.users_images%'
            upload_destination:  '%kernel.root_dir%/../web/images/users' #'%kernel.project_dir%/web/images/urgence'
            namer:
                service: vich_uploader.namer_uniqid