esprit_api:
    resource: "@EspritApiBundle/Resources/config/routing.yml"
    prefix:   /

baby_sitting:
    resource: "@BabySittingBundle/Resources/config/routing.yml"
    prefix:   /
sante:
    resource: "@SanteBundle/Resources/config/routing.yml"
    prefix:   /sante

scolarite:
    resource: "@ScolariteBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /user

user:
    resource: "@EspritApiBundle/Resources/config/routing.yml"
    prefix:   /api

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"